source 'https://rubygems.org'
ruby '1.9.3'

gem 'rails', '4.1.0.rc2'
gem 'sass-rails', '~> 4.0.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'rails-backbone'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bson_ext'
gem 'mongoid', '~> 4.0.0.beta1', github: 'mongoid/mongoid'
gem 'haml', '~> 4.0.5'
gem 'rails_admin', '~> 0.6.2'
gem 'bootstrap-sass', '~> 3.1.1'
gem 'haml_coffee_assets', github: 'jdnguyen/haml_coffee_assets'
gem 'execjs'
gem 'awesome_print', github: 'jdnguyen/awesome_print'
gem 'paperclip', '~> 4.1'
gem 'mongoid-paperclip', :require => 'mongoid_paperclip'
gem 'aws-sdk', '~> 1.3.4'
gem 'unicorn'
gem 'email_validator'
gem 'newrelic_rpm'
gem 'sanitize'
gem 'omniauth'
gem 'omniauth-facebook'

group :development, :test do
  gem 'rspec', '~> 2.14.1'
  gem 'rspec-rails', '~> 2.14.2'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'mongoid-rspec'
  gem 'factory_girl_rails'
  gem 'database_cleaner', '~> 1.2.0'
end